import type { Metadata } from "next";
import {  lexend } from "@/app/ui/fonts";
import "@/app/ui/globals.css";
import  Header  from "@/app/ui/components/header";
import  Footer  from "@/app/ui/components/footer";
import Banner from "@/app/ui/components/banner";

export const metadata: Metadata = {
  title: "Shopify Expert Developers | The SJ Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialised`}>
        <Banner/>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
